### ISSUE TITLE
Expand data model

### ISSUE THREAD

**Issue by codaich** [ELVIS-Project/simssadb#11]
Expand your data model outline at https://github.com/ELVIS-Project/SIMSSA-Database/wiki/Entity-Attributes to include all entities and relationships in the original DLfM 2017 ERD. Continue adding entity attributes as you think of them.  Make use of the content at https://ddmal.teamwork.com/#notebooks/179803. Don't feel you need to do everything yet, but start thinking about what should be prioritized, and keep track of what is done and what is not done yet.

Come up with a proposed update to the data model originally proposed at DLfM 2017 that we can use in our first implementation of the database, and discuss it with me for finalization. This update should include new entities and an outline of all relationships between all entities (including cardinality in both directions), and all attributes of all entities. Don't worry about making a graph for now; the approach you've already started on the Wiki is perfect at this preliminary stage.

**Comment by blueNoteb5** [comment]
## Musicologically and text-search important metadata:
- [ ] Title
- [ ] Composer
- [ ] Instrument/voices
- [ ] Geographical locations
- [ ] Periods of time
- [ ] Genre
- [ ] Religiosity
- [ ] Vocalization
- [ ] Bibliographic identifiers
- [X] Ordering of sections

**Comment by blueNoteb5** [comment]
## Entities, relationships and attributes associated with the musical notation used in Source entities:
- [ ] Chant (various types)
- [ ] Modal
- [ ] Black mensural
- [ ] White mensural
- [ ] Modern notation
- [ ] Original note values
- [ ] Diminished note values

**Comment by blueNoteb5** [comment]
## Entities, relationships and attributes associated with making sure are correctly understanding the amount of detail available in a symbolic encoding:

- [ ] Accidentals encoded
- [ ] Real octave
- [ ] Tuning system specified
- [ ] Written for transposing instrument
- [ ] Instrument/voice specified
- [ ] Tempo specified
- [ ] Precise rhythmic information specified
- [ ] Mensural notation
- [ ] Quantized
- [ ] Steady tempo
- [ ] Dynamic markings present
- [ ] Performance markings present

**Comment by blueNoteb5** [comment]
## Entities, relationships and attributes associated with text found on Source entities (and associated languages):

- [ ] Lyrics
- [ ] Title
- [ ] Editorial notes

**Comment by blueNoteb5** [comment]
@codaich please take a look at the update Wiki page, I've added attributes and promoted a few attributes to entities.

**Comment by blueNoteb5** [comment]
Cool, thanks.
However, please note that I didn't include any of the attributes, entities or relationships chains of provenance because I'm not quite sure how to implement those, even on a conceptual level.

**Comment by codaich** [comment]
Good question, I'm not sure. Maybe ask Claire or Nat if they're around, or Julie if they're not. That list is from a brainstorming session a year ago, so much of it did not come from me, and I don't remember exactly what everything was.
