### ISSUE TITLE
Return correct full person's name from Wikidata

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#137]
For example, `Johann Sebastian Bach` will be split into two entries from Wikidata, one as `Johann Bach` and the other as `Sebastian Bach`. We need to return only one `Johann Sebastian Bach` with the full name

**Comment by juyaolongpaul** [comment]
However, we actually have results for `Johann Christoph Bach I` and `Johann Christoph Bach II` from Wikidata when we search `Bach`. How should we restore `I` or `II` to differentiate between these two persons? Since they don't belong to either surname or given name. @julieemelyncumming

**Comment by emilyhopkins** [comment]
I think for our purposes those should be considered part of the last name.

(You're right that it's not technically part of the last name -- according to Chicago Manual of Style, it's a "generational suffix", and should be done like this for listing the last name first:

Bach, Johann Christoph, II.

But that's not really the situation here.)

**Comment by juyaolongpaul** [comment]
@blueNoteb5 Maybe we can develop a field for "generational suffix"? At least I can append it to the last name right now (although this might not be accurate).

**Comment by juyaolongpaul** [comment]
Makes sense. I can attach it to the last name at this point, and we can change it if needed in the future.
