### ISSUE TITLE
Re-design the musical work form

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#147]
Since section always belongs to at least one musical work, so it does not make sense if we create an "independent" section from the front-end. Instead, the section form should be inserted into musical work form.

**Comment by juyaolongpaul** [comment]
We can make the musical work page more similar with ELVIS DB `Upload A Piece`. However, we need to change the back-end of musical work a lot, and I need to work closely with @blueNoteb5. We will work on this once he is back on Monday.

**Comment by juyaolongpaul** [comment]
Now I am trying to design a mock-up form for uploading a musical work (associated with symbolic files). Although we need to change the back-end of musical work to really create an instance from the form, we can at least show the form for the demo for feedback.

**Comment by juyaolongpaul** [comment]
Now the main page looks like this:
![image](https://user-images.githubusercontent.com/9313094/44219946-3fcfc400-a14b-11e8-80e4-da93e535102a.png)
Next, I will add a plus sign next to `Title` and `Composer` to create `Variant titles` and different roles of contributors, respectively. 

Later on, I will add creation functionalities in case the entry of a field does not exist in the database (so the user needs to create a new entry on the fly).

**Comment by juyaolongpaul** [comment]
Now you can press `+` to create a variant title, and press `-` to delete one:
![image](https://user-images.githubusercontent.com/9313094/44231229-64d42f00-a16b-11e8-83a2-75fcb45b5e5a.png)

**Comment by fujinaga** [comment]
Not sure why there are two columns.
What happens if the window is narrow?

**Comment by juyaolongpaul** [comment]
You mean `Composition Start Date` and `Composition End Date`? They are borrowed from the ELVIS DB (as two columns). The whole page uses bootstrap so when the window is narrowed; these fields will adjust themselves to fit nicely.

**Comment by juyaolongpaul** [comment]
![image](https://user-images.githubusercontent.com/9313094/44286095-d7a9dc80-a235-11e8-84c9-5a38b916fa11.png)

Now we can confirm to create a new item which does not exist in the database, although now it still redirects to a different page, the core functionality is implemented. I will look into how to create a new item to the database directly (without redirecting) when the user clicks `confirm to add a new item`.
