### ISSUE TITLE
Adding the plus and minus sign to more fields like instrumentation

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#154]
So that we can specify what instruments are used for a piece

**Comment by juyaolongpaul** [comment]
Or this can be done by enabling multi-selections like this: 

![image](https://user-images.githubusercontent.com/9313094/44361920-6a908400-a48d-11e8-8833-9ae0966276e6.png)

We will discuss about this on the ELVIS meeting of August 21.

**Comment by juyaolongpaul** [comment]
In the end, we use multi-selection for genres, instruments, locations, etc. But for contributors, we use "add/remove" button. Now the upload page looks like this:
![image](https://user-images.githubusercontent.com/9313094/48460685-2d8f1180-e79e-11e8-80ed-59e504225f79.png)

Once we click "add" button on the contributor, a copy of this form will be inserted:
![image](https://user-images.githubusercontent.com/9313094/48460706-4d263a00-e79e-11e8-8241-8fcedd43da9f.png)

**Comment by fujinaga** [comment]
Is this interface running somewhere, so that we can play around with it?

Ich

**Comment by juyaolongpaul** [comment]
Yes, you can visit it using 132.206.14.123:8000 for now.

**Comment by fujinaga** [comment]
Neither the Download nor the Upload links work.
I also get an error when I tried to Sign up.

Ich

**Comment by juyaolongpaul** [comment]
Just fixed the sign up function (changed the bootstrap 3 into 4). Please try again.

**Comment by fujinaga** [comment]
I was able to create an account.
Upload works at the top menu bar but not on the main page (or the Download link).

Thank you,

Ich
