### ISSUE TITLE
Cannot create new instance of entity

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#172]
An error will pop-up when I try to create, say, a new genre as in type: 
![image](https://user-images.githubusercontent.com/9313094/47475411-2ef59b80-d7e9-11e8-9fb2-cf12118952fb.png)

This is because `get_absolute_url` is not defined in the model anymore (which is available in the previous version), which needs to fix. @blueNoteb5

**Comment by blueNoteb5** [comment]
This is because there is no view called new, and therefore no URL.

We need to write a "create" view for objects (like we talked about there are not in the ViewSets), and then hook up a /<entity_name>/new url

**Comment by blueNoteb5** [comment]
I had the method as an ``absolute_url`` property instead of ``get_absolute_url()``, I changed that, see if it is fixed.
