### ISSUE TITLE
Renovate "Upload A Piece" Page 

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#175]
This page needs to redesign so that everything about creating a musical work will be properly displayed, and all of them will be created **at once** when the user submits the form of the musical work.

**Comment by juyaolongpaul** [comment]
Now the page looks like this:
![image](https://user-images.githubusercontent.com/9313094/47940371-c8474080-dec0-11e8-8201-165b39174359.png)

**Comment by juyaolongpaul** [comment]
It looks like this: 
![image](https://user-images.githubusercontent.com/9313094/48581834-e6fdfc00-e8f0-11e8-878a-41c44cc2a0d2.png)

The user can create multiple new instances for genres and instruments, and a reminder of confirmation is displayed in the drop-down menu. The user can confirm by appending a comma in the end, then the user can select the new entry by clicking `test` (as an example) in the drop-down menu: 
![image](https://user-images.githubusercontent.com/9313094/48582077-8fac5b80-e8f1-11e8-89ee-540d764fc75c.png)

**Comment by juyaolongpaul** [comment]
Now, we can create a new contributor in the page by clicking "New Contributor", if the user cannot find one in the database (I will work on the style of the form later): 
![image](https://user-images.githubusercontent.com/9313094/48652305-cc995080-e9cc-11e8-9f46-d1c75406a95b.png)

Now, all the functionalities we talked about for the upload form is complete. The user now can create new contributors, new geographical areas, new instruments and genres. Auto-complete is added to all the necessary fields, with search function. 

Let me know if you have any feedback and advice!

**Comment by fujinaga** [comment]
> On Nov 16, 2018, at 6:29 PM, juyaolongpaul <notifications@github.com> wrote:
> 
> Now, we can create a new contributor in the page by clicking "New Contributor", if the user cannot find one in the database (I will work on the style of the form later):
> 
> 
You shouldn’t have the pink boxes with a minus sign when it doesn’t do anything. 
Have you checked this interface on a tablet or a smartphone?

> Now, all the functionalities we talked about for the upload form is complete. The user now can create new contributors, new geographical areas, new instruments and genres. Auto-complete is added to all the necessary fields, with search function.
> 
You can’t say functionalities are complete unless it’s all functioning with the proper data. 
You need to provide the lists to be used for auto completions, such as Composers’s names (e.g., from VIAF), geological ares, instrument names, etc.

**Comment by juyaolongpaul** [comment]
Thanks for reminding. Yes, I have not filled the database with the data from the authority control yet, and I will do it soon (as well as checking the website on the tablet or cellphone).

For the minus button, it is used to remove extra entries for titles, contributors, files and sections once the user creates too many entries by clicking the plus button, and the minus button won't work if we only have one entry for each category (maybe I need to hide the minus button in this case).

However, I implemented a different way of adding/removing the contributors. If this is the preferred way, I can do the same for titles, contributors, files and sections.

Obviously, this form needs further refinements in many ways, and I will keep improving it until people are satisfied with it.
