### ISSUE TITLE
Enabling to see the upload page without login

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#178]
So people can offer feedback to the design of the page

**Comment by juyaolongpaul** [comment]
Hi everyone, @fujinaga @emilyhopkins @codaich @julieemelyncumming @andrewkam @blueNoteb5 

The upload page is available here: http://132.206.14.123:8000/en/musicalwork/new/

Please let me know if you have any advice and feedback regarding the design of the page, as well as any additional fields you want to add. 

Thank you very much!

**Comment by emilyhopkins** [comment]
Thanks! I'll take a look and make some comments here. 

For the ordering of movements/sections, it should default to numbering them 1-whatever, you shouldn't have to enter the ordering manually (like the old interface...)

**Comment by emilyhopkins** [comment]
The pink buttons are taller than the lines they're on -- they should be the same height. 

There needs to be a bit of space between the field label and the field

**Comment by emilyhopkins** [comment]
Sources has a grey box with "------" in it when the page is first loaded -- field should be blank

**Comment by emilyhopkins** [comment]
The "New Contributor" button should not appear by default; it should only be triggered by a user entering a name that is not in the DB (like RISM)

**Comment by emilyhopkins** [comment]
The fields that have auto-complete or drop-down are boxes, the other fields have lines. 

Can they all be boxes instead?

There should also be some space between lines, the boxes shouldn't touch.

**Comment by emilyhopkins** [comment]
Why is there a "New Source" option? We aren't doing authority control for those are we?

There should be some auto-complete for titles though...

**Comment by emilyhopkins** [comment]
I don't think "Bologna Q15" is a portion -- it's a source. 

Also "Portions" is confusing in practise and needs better examples (I can work on this)

**Comment by juyaolongpaul** [comment]
> I don't think "Bologna Q15" is a portion -- it's a source.
> 
> Also "Portions" is confusing in practise and needs better examples (I can work on this)

I deleted the example, and it will be great if you can give some examples to explain it!

**Comment by juyaolongpaul** [comment]
> The "New Contributor" button should not appear by default; it should only be triggered by a user entering a name that is not in the DB (like RISM)

This is fixed in the last commit. The button's location changed for some reason, which I will fix later.

**Comment by emilyhopkins** [comment]
I don't think we're going to have much luck with authority control for sources? I can look into it for future stuff if we decide we want it... we only talked about using it for contributors and titles so far.

**Comment by juyaolongpaul** [comment]
Yea

> I don't think we're going to have much luck with authority control for sources? I can look into it for future stuff if we decide we want it... we only talked about using it for contributors and titles so far.

I took a look at Wikidata (our main authority control resource), and did not find the metadata we want for sources (A lot of them are not related to music at all). Yes, we can talk about this later.

**Comment by juyaolongpaul** [comment]
> > I don't think we're going to have much luck with authority control for sources? I can look into it for future stuff if we decide we want it... we only talked about using it for contributors and titles so far.
> 
> I took a look at Wikidata (our main authority control resource), and did not find the metadata we want for sources (A lot of them are not related to music at all). Yes, we can talk about this later.

@fujinaga reminds us about the choice of authority control resource. After discussing this with Emily, here is our plan:
(1) VIAF, in theory, should be more prioritized as the authority control resource. Although there are some shortcomings, we probably need to retrieval data from VIAF first.
(2) If we need more data, we could use Wikidata, which should be separated from the data we retrieve from VIAF.
I will create an issue for this.
