### ISSUE TITLE
Separate the pre-filled data from Wikidata

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#179]
Since we need to pre-fill the database from Wikidata, we think it is a good idea to isolate the pre-filled data and store them separately (This is not prioritized for now, but should be done sometime in the future).

**Comment by codaich** [comment]
I think it is important that (in the near term) we have authority-based auto-complete functionality in some sense, whether its downloaded and buffered offline or not.

**Comment by juyaolongpaul** [comment]
Yes, I already did this today, and since the page takes 10-15 seconds to load, @blueNoteb5 thinks we might want to store these entries separately (maybe we manage to load the page faster this way).

**Comment by emilyhopkins** [comment]
Takes 10-15 seconds to load from locally stored version or from Wikidata/VIAF directly?

**Comment by emilyhopkins** [comment]
I only ask b/c I thought last week's meeting we decided to have it stored locally already

**Comment by juyaolongpaul** [comment]
Yes, all the data is stored locally (pre-filled).
