### ISSUE TITLE
"Append comma to confirm the addition of a new..." should be replaced with checkbox

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#180]
Getting people to make lists (like of instruments) with a comma is fine, but using it to confirm a new addition to the DB is counterintuitive (like in the genres section)

Can we make a checkbox appear like in RISM Muscat? It makes it clearer what is going on.

**Comment by juyaolongpaul** [comment]
Yes, the ideal goal is to either click "confirm the addition of ..." as a link to confirm or show it as a checkbox, but I do not know how to do it yet (I have tried before and it does work as expected), so this is a work around, and I will take a look at this soon.
