### ISSUE TITLE
Instrumentation section text is outdated and conflicts with drop-down options

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#181]
The mouse-over comment is leftovers from the old DB I think? It recommends things that aren't in the drop-down. 

For the demo we can maybe focus on things that are easy to enter from the drop-down list but we still need to resolve how to make something like entering an orchestra more user-friendly.

**Comment by juyaolongpaul** [comment]
Yes, now I used the help text Gustavo has created in the back-end, but yes we need to modify the help text if needed.
