### ISSUE TITLE
Sources and portions incorrectly labelled (or something)?

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#182]
Currently sources has auto-complete/authority control features, and the mouse-over text is about collections (not sources)

Currently, Portions has mouse-over text about publication/source information. Isn't portion for stuff like page or plate numbers?

Shouldn't source and research collection have separate fields?

Maybe I'm missing something about the design but right now the fields don't match their descriptions which makes it hard to use.

**Comment by juyaolongpaul** [comment]
@blueNoteb5 What do you think?

**Comment by juyaolongpaul** [comment]
What I understand at this point (after Gustavo's explanation) is that a source is a collection, and a portion is a part from the source that the user specifies

**Comment by juyaolongpaul** [comment]
We need some help text to explain the concept of the source (why it is called `collection of sources` in the back-end again? This also creates some discrepancies for the help text since the help text of creating a source refers to `collection of sources`, not `sources` @blueNoteb5)

**Comment by emilyhopkins** [comment]
OK, but something like "Bologna Q15" should be a source -- wouldn't portion be like "pp. 14-27" or something?
