### ISSUE TITLE
Upload form wording and example updates

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#187]
I can't run the DB on my home machine any more b/c you are using Python 3.6 stuff now so I did some edits on a screenshot:

![upload form notes](https://user-images.githubusercontent.com/13374693/49109565-08e47080-f259-11e8-97a1-0fa8b82c2031.png)

I didn't have much to add about sections that I haven't said already (numbering needs to be automatic like the old DB)

Please ask if anything is confusing!

**Comment by juyaolongpaul** [comment]
The grey box is removed.

**Comment by juyaolongpaul** [comment]
@emilyhopkins Hi emily, it will be great if you can take another look at the form now, which can be visited [here](http://132.206.14.123:8000/en/musicalwork/new/).

Now the `Attach To` button under the section of "File" creates options which are dynamically created and updated from the titles of sections as the user types.  You can check out this function as well.

Please let me know your advice and feedback, thanks!

**Comment by emilyhopkins** [comment]
Thanks Yaolong! Please feel free to ask for clarification on any of this. Some notes:

**Composer:**
- new contributor should just be the label for the plus sign, and the plus sign should probably go on the left-hand side on the left of the contribution role ( + Composer ____name______)
- it should allow min. ten contributors, ideally more should be theoretically possible, but three is not enough.
- adding a new composer to the database should be more like the RISM checkbox thing, the new contributor button is confusing because it’s not consistent with how we add things later and it doesn’t go away if you delete the stuff in the field. 
- is it possible to make the drop-down that appears (“Click ‘New Contributor’ to confirm the addition”) be the thing that they click to confirm the addition? 
- that being said I still prefer the RISM checkbox. It’s clearly separated from the main form, and is enough of a ‘big deal’ to prevent accidental additions of new stuff, but is integrated enough not to distract from the main task at hand.

**Date**
No need for a date incrementing button. No one wants to enter a date by clicking a button 1700 times and it’s easier to fix small errors with typing :)

**Certainty of Attribution**
You only half-changed it :) 
So either:
Instead of “Yes” put “Certain”
Instead of “No” put “Uncertain”
OR change it to have the question "Is this attribution certain?" and then Y/N
Change the spacing so it’s clear that the boxes are associated with the words, they’re just floating nowhere right now. (see below for example)
Certain []   Uncertain [] 

**Instrumentation**
Maybe avoid using appending a comma to confirm new instrument in DB b/c it implies a list (e.g. a piece for “oboe, flute, piano”)
Same goes for other fields with multiple possibilities (Genres as in type, Genres as in style)
RISM style checkbox is ideal here.

**There is still some spacing stuff that makes it hard to read. Like this:**

Title:e.g.. Symphony No. 3, Op. 55

should be:

Title e.g.. Symphony No. 3, Op. 55

(You can leave the colon out, and make sure there is a buffer of space after the field name or inside the field, whichever is fine). This happens several times, they all need the same fix.

**Why are some fields lines and some fields boxes?** 
It seems sort of random right now…

**Under “additional information”**
instead of “These fields make it easier to find the piece using the database search engine”
it should say:
“Please enter as much information as possible to make it easier for others to find the piece”
or something like that.

**Under Sections:**
Current text:
“If the musical work is divided into sections, declare them in this table. Please enter titles for all sections, even if you will not be uploading files for all of them.”
Replace with:
“If the musical work is divided into movements or other sections, list them below. Please enter names for all sections, even if you will not be uploading files for all of them.”

For the actual movement entry, please look again at how the old DB does it. The ordering should be automatic and I don’t think we need an incrementing button again.

We’ll need to add some more explanatory text. This can be my job. I’ll try to get the DB running on my new work computer this week, maybe you can help. 

Provenance needs an example or some explanation. I’m still unclear on what we actually want users to input here or I’d make a suggestion!

Thanks!

**Comment by juyaolongpaul** [comment]
Thanks @emilyhopkins  for the detailed comments! I will go through it after tomorrow's DB meeting.

**Comment by juyaolongpaul** [comment]
@emilyhopkins I have been trying to change the schema of "append comma to confirm the addition of an item" to RISM style. However, it appears to be a much harder problem as for now. There might be an easier solution once I have more time to investigate into this. For now, I change the comma into semicolon (let me know if there is a better symbol for this) so we can input a possible entry like `piano, flute, violin`.

**Comment by juyaolongpaul** [comment]
This is how the form looks like now:
![image](https://user-images.githubusercontent.com/9313094/52830200-c5521380-309d-11e9-97af-3498674aab1a.png)

**Comment by emilyhopkins** [comment]
I'm going to close this; we're not working with this form any more really and we can make other issues for ongoing updates.
