### ISSUE TITLE
Write logic to add musical works on backend using front end form

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#194]

**Comment by juyaolongpaul** [comment]
Does this mean that the asynchronous call for jSymbolic to work in the background? I don't know what the title means.

**Comment by emilyhopkins** [comment]
I'm guessing this is just integrating the form (which @juyaolongpaul you used to be mostly working on) with the backend (which used to be only @blueNoteb5) ? I think there are other issues that address the jSymbolic call specifically
