### ISSUE TITLE
Works / Sections / (maybe) Parts can have multiple titles, and each should have an identified language

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#20]

**Comment by blueNoteb5** [comment]
@codaich @fujinaga 
I'm not clear on why we need to keep track of the languages of the title?

Right now what we have is: 
* Preferred Title
* Alternative Titles

Laura and Emily got this encoding for titles from the library standards I believe

**Comment by codaich** [comment]
I think the title language requirement originally came from @julieemelyncumming , or maybe @fujinaga, they might be better able to answer your question about the language of titles?

If the authority control specifies the various languages, then we're fine. However, taking a superficial look at VIAF, it seems that it only specifies the institution and associated country of each title, not the language (which is ambiguous if we're dealing with multi-lingual countries, which almost all are). I'm fine with not explicitly specifying the language of the title, as long as Julie and Ich are.

Re. multiple title names, the authority control might also handle this for us? Although annotators might want more direct control. What do you think, @julieemelyncumming and @fujinaga? Should we only permit multiple titles in the sense that the authority control URI can itself specify multiple alternative titles, or should contributors be able to explicitly specify multiple titles themselves?

**Comment by emilyhopkins** [comment]
How quickly are we going to run into titles that don't have anything in VIAF? (We may have to allow for some free entry on the users' part if there are pieces that won't have a VIAF entry...)

**Comment by blueNoteb5** [comment]
How extensive is VIAF in terms of keeping track of music works?

But my main question is why we need to keep track of the language of the title, as in, would anyone search for something like "sonatas with a title in German"?

I understand that we need to keep track of language for pieces with lyrics, but I'm still confused about the title issue.

**Comment by blueNoteb5** [comment]
Closing the issue, see: https://ddmal.teamwork.com/#notebooks/179927
