### ISSUE TITLE
Add GNU GPL license to repo?

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#217]

**Comment by dbs** [comment]
Yes, please add an explicit license for the code, for example a LICENSE.md file containing the [GPL 3 text](https://www.gnu.org/licenses/gpl-3.0.md). This will help other developers understand what they can do with your code and under what terms the code they contribute will be used.

**Comment by emilyhopkins** [comment]
It's done, thanks, was on the backburner for needlessly long time! 

Thanks for your interest in the project.
