### ISSUE TITLE
Zenodo integration test

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#232]
- upload madrigal dataset and associated metadata
- make sure it integrates as we need it to (corpus functionality might not exist in time but we should be able to figure it out.)

**abstract deadline april 18**
report back to team April 2

**Comment by emilyhopkins** [comment]
This is in-progress; I've sorted out all the metadata and was uploading the files when I realized just integrating with the GitHub repo may be a more sensible move since it replicates the file/folder structure. Otherwise I just have to make a ton of zip archives since there are so many different formats organized separately.

**Comment by julieemelyncumming** [comment]
Makes sense!  Julie

Julie E. Cumming
Schulich School of Music, McGill University
555 Sherbrooke St. West
Montreal, Quebec H3A 1E3 Canada
Wirth Music Building, Room A 628; 514-398-4400 x00313
julie.cumming@mcgill.ca<mailto:julie.cumming@mcgill.ca>

**Comment by emilyhopkins** [comment]
Hi everyone!

So I linked the GitHub repo and made a release: 
https://zenodo.org/badge/latestdoi/133998137

But then I realized that it would show up under "software" instead of datasets, and I also figured out a better way to compress our files and preserve the folder structure.

So I made a dataset release too:
https://zenodo.org/record/2635499#.XK4BVtEpBtQ

What do you think? Connecting back to GitHub makes sense in some ways since I know we're not the only ones using it for symbolic music files. Maybe it's a good plan to both sync the repo and create a separate data set release.

Feedback on workflow/metadata appreciated! 

The integration with SIMSSA DB is basically that we can use the dataset DOI to associate pieces with a study. We could have a JLSDD corpus on SIMSSA DB and files that are the same files as we have on Zenodo/GitHub can be linked back to the data set.

**Comment by julieemelyncumming** [comment]
Dear Emily – I would love to sit down with you and get a full description of this whole process.  Maybe we could make that the topic of the next ELVIS meeting – how to put a research corpus on Zenodo.

I don’t feel equipped to comment at this point.

Julie

Julie E. Cumming
Schulich School of Music, McGill University
555 Sherbrooke St. West
Montreal, Quebec H3A 1E3 Canada
Wirth Music Building, Room A 628; 514-398-4400 x00313
julie.cumming@mcgill.ca<mailto:julie.cumming@mcgill.ca>

**Comment by juyaolongpaul** [comment]
Hi Emily,

Thank you for the work! I agree with Julie, and I would like to know more about this.

**Comment by emilyhopkins** [comment]
Sounds good! 

I also met someone working on Dataverse (https://dataverse.org/) when I was at LibrePlanet back in March (Philip Durbin, https://scholar.harvard.edu/pdurbin/home) and talked to him a little about our project. I'm going to follow up with him now to get a better sense of how Dataverse is different and whether it might be a good fit for our needs instead/as well.

**Comment by emilyhopkins** [comment]
I'm going to close this one for now since I think based on the ELVIS meeting we're happy with using this as a strategy for now (and certainly for MEC)
