### ISSUE TITLE
Composers should have multiple names

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#24]
@codaich I'm adding this issue because it is on the teamwork tasks assigned file, but I thought we were going to use an authority control to keep track of an "official" name and then just link the users to alternative names using the URI for the composer?

**Comment by codaich** [comment]
@blueNoteb5 yes, just a single URI to the authority control is fine as long as the URI includes references to name synonyms (if any). It gets a bit more complicated if the encoder enters a name that we can't find an authority control URI for, and wants to enter multiple names for this composer. In this case, maybe we could make our own authority control URI (which will include synonyms, if specified). So, in the end I think you're right that the composers _field_ can have just one value (i.e. the authority URI).

**Comment by fujinaga** [comment]
I don't think we should allow encoders to enter names that are not on the VIAF or the ISNI list. We could have an autocomplete dropdown list to help the encoder (e.g., https://www.jqueryscript.net/form/Autocomplete-Dropdown-List-Plugin-jQuery.html and https://www.jqueryscript.net/form/Autocomplete-External-Data-jQuery-Pughound.html)

**Comment by blueNoteb5** [comment]
Ok, I'll look into implementing something that looks up info from an authority control

**Comment by codaich** [comment]
@fujinaga and @blueNoteb5, I think that there’s an unresolved tension here between usability / accessibility / factors affecting willingness to contribute for musicologist (the ones who we need to supply data and metadata) and the correctness / consistency of the data. I absolutely agree that we should use dropdown menus and other recommendation techniques as much as possible to encourage contributors to conform to authority controls, but I’m worried that forbidding users to contribute if they don’t conform could severely hamper the attractiveness of the database to its target users. I think Julie, you and I should all meet to resolve this issue when we’re all in town at the same time, but in the meantime I think it’s important to avoid any design or implementation decisions that would ultimately make it impossible to enter metadata not on the VIAF or ISNI list (we can always forbid this at a later point if that’s the decisions we collectively end up making).

**Comment by codaich** [comment]
Sounds good to me, and we can always remove the "other" option later (before releasing) if that's what we decide is best.

**Comment by julieemelyncumming** [comment]
I agree!  Julie

Julie E. Cumming
Schulich School of Music, McGill University
555 Sherbrooke St. West
Montreal, Quebec H3A 1E3 Canada
Wirth Music Building, Room A 628; 514-398-4400 x00313
julie.cumming@mcgill.ca<mailto:julie.cumming@mcgill.ca>

**Comment by fujinaga** [comment]
The "Other" option is fine with me.
