### ISSUE TITLE
Portion needs to be optional and have an example

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#262]

**Comment by juyaolongpaul** [comment]
Now it is optional in the newest version of the DB:  http://132.206.14.204:1337/en/, and yes we need to actually develop help text for all the fields (portion might need extra explanation). We can add the style of the hovering help text back from ELVIS DB. Let us know how urgent this is (it seems to me that this can wait for later after a few urgent issues are resolved).

**Comment by emilyhopkins** [comment]
Maybe tomorrow we can get it set up so I can try to add the example text for everything. The field names that come from the DB I can't change so easily but I think I can add the example text at least.

I don't think we need hovering text necessarily, but more explanations would be good. I'll follow the feedback we've received so far.

**Comment by emilyhopkins** [comment]
Portion should be moved to File instead to make mapping to sources clearer
