### ISSUE TITLE
Change font colour in language drop-down menu

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#263]
It's apparently currently white-on-white!

Do we even still have multilingual support?

**Comment by juyaolongpaul** [comment]
We have the framework of the multilingual support, but we need to work on it and obviously this is not the immediate priority. I will label this as the long-term, and remove the language drop-down menu from the interface for now (on Compute Canada).

**Comment by emilyhopkins** [comment]
This is fine by me! Removing the menu is a good solution for now.
