### ISSUE TITLE
Search or metadata problems with genre

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#266]
Ian said that when he searched for chansons and motets nothing came up, even though the motet and chanson composers are in the dataset.

Is this a problem with our metadata for these uploads (in which case we need to revise our batch upload process), or a problem with the actual search?

**Comment by emilyhopkins** [comment]
Cory said:

"Metadata search needs to work (when I enter "Josquin" or "Missa" in the header bar search box I get nothing, even though both are in the DB when I browse). It does work for files I entered myself, though. However, if I search for "Cory" I also get some stuff returned that I 
shouldn't."

**Comment by emilyhopkins** [comment]
Need to add genre metadata, etc, to words that get searched (chansons should be a filter but should also be searchable)

**Comment by blueNoteb5** [comment]
Closing since I'm collecting similar issues into issue #287
