### ISSUE TITLE
Search filters not responding

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#267]
According to Ian: when you click on any one of these buttons, it doesn't refine the search any further: everything stays the way it is on the page. So that does not appear to be working. 

![Screenshot of Results Filter](https://user-images.githubusercontent.com/13374693/57728798-bcec8300-7662-11e9-965b-8fd0e4eab66b.png)

**Comment by juyaolongpaul** [comment]
Duplicates of #259, which @blueNoteb5 is currently working on. Close now.
