### ISSUE TITLE
Finish deployment for internal testing

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#268]
So that people can visit http://db.simssa.ca/ to see the official version of the DB

**Comment by codaich** [comment]
Is it going to be https://db.simssa.ca or http://db.simssa.ca ?

**Comment by emilyhopkins** [comment]
Neither is loading the site for me right now...

**Comment by juyaolongpaul** [comment]
I will be working on this issue from now until I leave (from Aug. 18 to Sep. 8), so that we will have a functional database for internal testing deployed on the DEV server (as Cory suggested, which I think is very helpful). 

One thing we need to figure out is what's the best practice to host not only symbolic files, but also CSV files and jSymbolic (these files probably won't go to our Github repo), and if they are stored in difference places, what's the best way to put them together automatically as easy as possible (I will work on writing script to do this automatically, and work with Alex).

At the same time, I will begin to write documentations for deployment so Gustavo will be able to upload new features and deploy the newer version once to the DEV server when I am gone.  

As of now, here are the things that won't be available in the internal testing version (because it will be really hard to finish them by Aug. 18):

* Downloading cart
* User login and tracking (e.g., tracking the uploaded musical works, the downloading cart and permissions for each user)
* Upload form

For the remaining issues on Github, we will try to finish them as many as possible, and we will inform you once the internal testing version is ready. 

Please let me know if you have any questions or comments, thanks!

**Comment by codaich** [comment]
I thought we had agreed that we were storing the CSV, ARFF and XML (values and definition) files for each symbolic file directly in the database (in addition to the DB's feature value tables)? And that we would automatically replace these files (and the table values) as part of the jSymbolic version update script? They won't get archived in the DB itself (i.e. they'll be gone forever after a jSymbolic update), although they could potentially be archived on Zenodo along with all other experiment files (and symbolic files themselves) for individual experiments.

OK and understood for everything else.

**Comment by juyaolongpaul** [comment]
Hi Cory, I agree with what you said. For CSV files, I mean the ones saving the metadata for our high-quality datasets (i.e., JLSDD, RenComp7 and Florence), not the feature files extracted by jSymbolic, which is reproducible. Like you said, we will only store the significant version of the features files if they are attached to a research publication, which will be archived in Zenodo. 

Hope it helps.

**Comment by codaich** [comment]
OK, sounds good, thanks for the clarification.

**Comment by juyaolongpaul** [comment]
Now our high-quality datasets are served as a separate [repo](https://github.com/DDMAL/sample_data), which acts as a submodule of our main repo (`simssadb`), as suggested by Alex. I also add jSymbolic to our main repo as well. These two steps should simplify our deployment process.

**Comment by juyaolongpaul** [comment]
Hi everybody, now the newest version of the DB is deployed on the DEV server: http://132.206.14.204:1337, where all three datasets are pre-filled, and it contains most of the new functionalities Gustavo has finished recently (e.g., date search, person can be filtered by contribution roles, sorting results, etc.). This will be the internal testing version we can deliver before I leave.

Please give a try, and if you have any suggestions, you can either email us, put notes on [Teamwork](https://ddmal.teamwork.com/#projects/315325/links), or create Github issues. 

At the meantime, I will inform Gustavo how to deploy the DB on the server, so that he can deploy the newer version of the DB when I am gone, and I will create Github issues for the issues that I found out are not resolved yet. 

Thanks everybody!
