### ISSUE TITLE
Pre-fill the DB with a few high-quality datasets

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#269]
We must have JLSDD, RenComp7, and MS Florence 164-167. Optionally, we can upload Bach and Praetorius chorales, and some Frescobaldi pieces before/after the MEC presentation.

- [x] RenComp7
- [x] MS Florence 164-167
- [ ] JLSDD

**Comment by emilyhopkins** [comment]
I'm working on having JLSDD, RenComp7, and Florence in Zenodo so we can show that integration as well. Then any others from Sam or Ian can be a bonus.

**Comment by juyaolongpaul** [comment]
Currently, the DB looks like this when batch uploading RenComp7:
![image](https://user-images.githubusercontent.com/9313094/57827650-15f90b80-7776-11e9-80ca-5beecc472f42.png)

![image](https://user-images.githubusercontent.com/9313094/57827991-be5b9f80-7777-11e9-93d3-fef3fcf70a11.png)


![image](https://user-images.githubusercontent.com/9313094/57828059-05e22b80-7778-11e9-84b5-86abef8215e0.png)


I will upload these files to the dev server soon, with all features extracted so you can view them and see whether the metadata is of high-quality.

Next, I will work on the JLSDD data set.

**Comment by juyaolongpaul** [comment]
I just uploaded the whole Florence 164-167 dataset. Now each piece has four symbolic files:

![image](https://user-images.githubusercontent.com/9313094/57903182-dea06280-783a-11e9-8a35-7ff5a7d6a005.png)
