### ISSUE TITLE
Search display: works vs sections

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#274]
Search results need to differentiate work and section results

From Cory: 

> I added a work with an overall MIDI file, as well as MIDI files for 
> each of the two sections (by Cory McKay). When I search for it, there's 
> no way to see what is a section and what is a work. They all just have 
> the work title.

**Comment by blueNoteb5** [comment]
Closing since I'm collecting similar issues into issue #287
