### ISSUE TITLE
Add more metadata for search templates

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#287]

**Comment by blueNoteb5** [comment]
@emilyhopkins I've added metadata for name and location of all types of contributors (arrangers, composers, etc)

I've also added metadata for the source/collection title.

So searches like this now work:

- "Bach"
- "baroque"
- "midi"
- "Florence 164"
- "Leipizig"

The metadata for work titles, genres (types and styles), instrumentation file type was already in there, but it might not have worked properly when we gave out the link for testing.

Is there anything missing that I should add?

**Comment by emilyhopkins** [comment]
Let's start with this but be open to suggestions from testers -- let me know when it would be useful and we can contact Sam and Sylvain to do some search testing (either on their own or in a session where you observe them and they talk about what they're thinking as they try to find stuff)
