### ISSUE TITLE
CSV template to correct the metadata from the existing files in the SIMSSA DB 

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#296]
As Gustavo and I discussed yesterday, I will provide a template to export the metadata we need to check into the CSV file for musicologists to correct. I will also provide the scripts so that:
* The existing metadata in the DB can be auto-filled into CSV file(s).
* Once musicologists finish correcting, the script will automatically parse the CSV file and update the metadata in the DB accordingly.

**Comment by emilyhopkins** [comment]
Waiting on Ian for JLSDD data to finish this

**Comment by juyaolongpaul** [comment]
I closed this issue for now since all three datasets have been modified and added to the DB. What I am going to do next is to host these symbolic files through a different repo and link to this repo as a sub-module for deployment.
