### ISSUE TITLE
Add date search functionality

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#326]

**Comment by blueNoteb5** [comment]
- [ ] Add slider to form
- [ ] Write code to read dates from all works and create range for slider
- [ ] Write code to filter based on range selected

**Comment by blueNoteb5** [comment]
@emilyhopkins 
I've been testing a slider I built for the year functionality and I'm not too sure it will work very well.
The slider is not very large so if we have a range of dates larger than 100 years, it either becomes impossible for the user to choose a precise date (i.e. choosing 1681-1689 would not work, it would have to be 1680-1690) or we have to many "steps" in the slider that makes it difficult to use (more than about 100 and the slider becomes very finicky).

I was thinking of just using two number input boxes for min and max date, and the user just types the years they want, would that still be acceptable?

**Comment by emilyhopkins** [comment]
I think that could work

Is it possible/not too onerous to have default slider that only goes down to every 10 years (which is actually pretty good for many purposes) but then have those boxes be editable?

so a combination of the two, like below:

[1690]-------||------------[1710]

(This is probably what the normal date sliders look like, just with editable boxes...)

Does the slider bar resize depending on what you click? Do you edit both ends of the timeline? How does that work?

**Comment by blueNoteb5** [comment]
Something like this:
![Screen Shot 2019-08-05 at 14 34 52](https://user-images.githubusercontent.com/22383576/62486823-39888c80-b78e-11e9-81bf-e929e174fcc5.png)

**Comment by emilyhopkins** [comment]
The slider has a more "browse-y" feel but if this is straightforward enough to implement it's certainly good enough for this round of the DB! Thanks.

**Comment by blueNoteb5** [comment]
> I think that could work
> 
> Is it possible/not too onerous to have default slider that only goes down to every 10 years (which is actually pretty good for many purposes) but then have those boxes be editable?
> 
> so a combination of the two, like below:
> 
> [1690]-------||------------[1710]
> 
> (This is probably what the normal date sliders look like, just with editable boxes...)
> 
> Does the slider bar resize depending on what you click? Do you edit both ends of the timeline? How does that work?

The slider has a gradation, that is how many "steps" it has. For the features I always leave it a 100, (you can pick from 100 different values between the max and the min) but for the dates it would depend on the search results, since we are now dealing with integers. 

The slider does not resize depending on what you click, but you can choose the min and max, so yes, you can edit both ends, just like the features (it's the same widget).

I'm not sure how to construct the slider with the editable boxes you've mentioned, although I like the idea. I'm sure it can be done with JavaScript but I'm not sure that it would be the best use of my time right now since it would probably take a while because my JavaScript skills are shaky at best.

**Comment by blueNoteb5** [comment]
@emilyhopkins Ok I'll do the boxes, thanks!

**Comment by juyaolongpaul** [comment]
Currently, when we search `1594` in `Composition Year From`, these Palestrina pieces do not show (they should show).

![image](https://user-images.githubusercontent.com/9313094/63183684-9b18e880-c023-11e9-9ae6-4a7fdde3f394.png)
