### ISSUE TITLE
Person list view should have section specifying each contribution role

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#334]
Currently, poets and composers are in the same list, where we don't know who are composers and who are poets, and also now poets do not have badges specifying how many music works they authored:

![image](https://user-images.githubusercontent.com/9313094/62395880-8de9fd00-b53f-11e9-8eb5-b902abf23d04.png)

What I suggest for now is:

- [ ] Separate each contribution role as different sections of this view

- [ ] Adding badges to all people (not only just composers) with the number of musical works they contributed to

**Comment by blueNoteb5** [comment]
A person can be both an author of text (poet) and a composer, for different musical works or for the same work, so it doesn't make sense to have separate lists for them

**Comment by emilyhopkins** [comment]
Could we leave it as badges but add a filter for contribution type? I know some people will have more than one but it will still e.g. get rid of a lot of poets if people mostly want composers...

**Comment by blueNoteb5** [comment]
Sure, we could add filters in the list view

My idea would be that if you filter by composers it would show everyone that has at least one contribution as composer, even if they have other types of contributions as well.

The same would apply for other types of contributions.

@emilyhopkins @juyaolongpaul  Would that be a good solution?

**Comment by emilyhopkins** [comment]
I think it's certainly good enough to use for the first version of the DB; people can test it out and we can see if it's confusing. Mostly I'm thinking we want to prioritize finding composers since we don't have  ton of files with texts anyways.

**Comment by blueNoteb5** [comment]
All right, I'll start implementing that

**Comment by juyaolongpaul** [comment]
I agree with Emily. Sounds like a good plan for now.
