### ISSUE TITLE
When the file is attached to sections, the detailed page should not show its linking to musical work

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#336]
An example looks like this:

![image](https://user-images.githubusercontent.com/9313094/62396310-da820800-b540-11e9-9d68-8ef54cbe2ea9.png)

This symbolic file is attached to the section of "Agnus II", but in the detailed page of this file, it still shows the link to musical work, and it shows "None". The desired result should be showing the link to section, and it links to "Agnus II".

**Comment by blueNoteb5** [comment]
The showing none is a mistake but I still think it should show a link to a section and the musical work that the section belongs to.
