### ISSUE TITLE
Deploy the dev server on ComputeCanada

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#367]

**Comment by juyaolongpaul** [comment]
Now the DB can be visited at [db.simssa.ca](http://db.simssa.ca). It has some issues extract features for certain files, but I will open another issue for it and close this one for now. When the features can be processed for all the files for the DB, I will let the team know, so perhaps we can start with the internal testing.

**Comment by juyaolongpaul** [comment]
Many thanks to @deepio for setting up the Nginx router!

**Comment by juyaolongpaul** [comment]
Now the DB can be visited at [db.simssa.ca](http://db.simssa.ca), with features extracted. It should represent the up-to-date DB for internal testing.
