### ISSUE TITLE
Make sign up send emails to confirm user during login

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#41]
Maybe also have a CAPTCHA?

**Comment by vigliensoni** [comment]
@juyaolongpaul 

You committed your email credentials to the repository. Never do that!

**Comment by juyaolongpaul** [comment]
Changed the password, and I will delete the last commit from remote and commit from my local machine again. Thanks!

**Comment by juyaolongpaul** [comment]
I will create a new email account for verification and add it to the lab wiki later.

**Comment by vigliensoni** [comment]
Don't add this information to the repo
