### ISSUE TITLE
Implement field auto-population from authority control

### ISSUE THREAD

**Issue by andrewkam** [ELVIS-Project/simssadb#44]

**Comment by emilyhopkins** [comment]
Muscat (by RISM) links to VIAF for personal name authority files, and their code is on GitHub. It's a rails app but might still be worth a look if you haven't seen it already. 

http://www.rism.info/community/muscat/

https://github.com/rism-ch/muscat

(I'm also going to the Muscat workshop at IAML so let me know if you have questions you want me to ask them for you!)
