### ISSUE TITLE
Add localization (many languages) to the front end

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#51]

**Comment by blueNoteb5** [comment]
@fujinaga said that this would be great for the demo if we can do it :)

**Comment by juyaolongpaul** [comment]
@fujinaga It is already done in my `feature/front_end_template` branch, which supports seven languages (English, French, Japanese, Chinese, Korean, Arabic and Spanish). Let me know if you want to add more languages. I will refer my commit to this issue once I finish merging my feature branch into develop branch.
