### ISSUE TITLE
Write up brief descriptions (and outlines of assumptions) for all entities and attributes

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#60]
* Including assumptions
* For each, highlight potential problems to be aware of where appropriate

**Comment by blueNoteb5** [comment]
@codaich I've added a ``help_text`` keyword argument to every field in every model in the database. These ``help_text`` arguments can be used in the front end to explain things to the user but they can also be used as documentation (as per [Django docs](https://docs.djangoproject.com/en/2.0/ref/models/fields/#help-text)).

The Django admin page in fact automatically generates documentation for all the models and uses the ``help_text`` to do so. It looks like this: 
![screen shot 2018-06-28 at 4 17 50 pm](https://user-images.githubusercontent.com/22383576/42058797-7c72f5bc-7aef-11e8-8b19-0a35e5c88abf.png)

I figured this was the best way to document things because then it is right in the code and we don't need to keep a separate document, and we are sure that we are getting documentation for every single field. Right now I'm looking for a way to export the Django admin auto generated documentation so that everyone can see it easily.

Is this enough in terms of documentation or should I still do a spreadsheet/chart?

**Comment by codaich** [comment]
@blueNoteb5 This is a nice way of generating the documentation, I'm glad you did it. However, it would also be good to have a chart or web site that could be posted and which users could refer to that includes everything, including definitions of entities (not just attributes). If it can be auto-generated, like what you're doing, that would be perfect. Kind of like javadocs, for example. Which attributes are primary keys and foreign keys should also be indicated.
