### ISSUE TITLE
Clarify the collection idea of the old ELVIS DB, and should we keep it?

### ISSUE THREAD

**Issue by blueNoteb5** [ELVIS-Project/simssadb#80]

**Comment by emilyhopkins** [comment]
Isn't it the same as "research corpus" in the new data model? Collection was a user-created grouping -- so often a particular experimental study or whatever but could be "My favourite wind quintets" or "cool oboe repertoire" or whatever too.

**Comment by blueNoteb5** [comment]
Ok, that makes sense, we'll just use the same front end things of the old and rename it, thanks!
