### ISSUE TITLE
Don't display Religiosity boolean values on the front end

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#86]
Currently it shows "True" or "False"

Should show "Sacred", "Secular", "Not applicable"

Front end can have three drop down choices. Back end has T/F/Null?

**Comment by juyaolongpaul** [comment]
Exactly @emilyhopkins, and I can add a drop-down choice for religiosity when we try to enable the user to upload a piece.

**Comment by emilyhopkins** [comment]
This now shows Yes/No on the database based on today's demo -- please update as above (before the demo next week if possible since we've discussed this with Julie too). Thanks!

Religiosity
- Sacred
- Secular
- Not applicable

**Comment by emilyhopkins** [comment]
Sorry -- according to today's meeting should actually be (in all places):

Sacred/Secular
- Sacred
- Secular
- Not applicable

**Comment by juyaolongpaul** [comment]
Yes, I will change that and refer to the ELVIS DB for other parts as much as possible. Thanks!

**Comment by juyaolongpaul** [comment]
@blueNoteb5 Please make sure we deal with this before the demo as well. Thanks!
