### ISSUE TITLE
Fix date display for composer and piece

### ISSUE THREAD

**Issue by emilyhopkins** [ELVIS-Project/simssadb#88]
Currently if nothing is entered it will display "Jan. 1" -- make it so nothing shows up on the front end instead.

**Comment by juyaolongpaul** [comment]
Thanks for the issues as reminders @emilyhopkins, and I will look on them soon.

**Comment by juyaolongpaul** [comment]
Issue fixed, and the front end looks like this:

Composer list:

![image](https://user-images.githubusercontent.com/9313094/42344367-2609588a-806a-11e8-97d3-1525091a6d2a.png)

Composer detail info: 

![image](https://user-images.githubusercontent.com/9313094/42344376-2efad95a-806a-11e8-9733-66cabbd4740a.png)

**Comment by fujinaga** [comment]
The dates for each piece, which is same as Composer’s dates look funny.

Ich

**Comment by juyaolongpaul** [comment]
I will talk to the team about how the date of composition is generated. It seems like the composer's date is used as the default if the date of composition is not specified.

**Comment by juyaolongpaul** [comment]
The ELVIS DB also contains the same data (see the screenshot), which SIMSSA DB inherits:
![image](https://user-images.githubusercontent.com/9313094/42381619-a6dcd2ee-80ff-11e8-8e3c-202e90c41178.png)
We might need to investigate why it is there in the first place.
