### ISSUE TITLE
Cannot obtain the collection of musical work since the source is not working

### ISSUE THREAD

**Issue by juyaolongpaul** [ELVIS-Project/simssadb#92]
I cannot add the collection where a musical work belongs to since the collection is linked to source and source is linked to musical work. However, since the source is empty because of no symbolic file, I cannot add the collection of a musical work at this point.

**Comment by emilyhopkins** [comment]
In the issue title you say the source is not working, but the comment seems to suggest that it hasn't been uploaded yet -- can you clarify?

However, I think we should also be able to add a musical work with no files attached(?)

**Comment by julieemelyncumming** [comment]
We have a lot of works with no files attached in the old database, so I think it does make sense to add the metadata and then upload the piece …  that should be clear in the search results, though.

Ideally the search results would immediately show whether there is a file and what the format is.

Julie

Julie E. Cumming
Schulich School of Music, McGill University
555 Sherbrooke St. West
Montreal, Quebec H3A 1E3 Canada
Wirth Music Building, Room A 628; 514-398-4400 x00313
julie.cumming@mcgill.ca<mailto:julie.cumming@mcgill.ca>
